version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    env_file:
          - development.env
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - development.env
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"
